# **The second In-class-exercise**


(1) Write a Python program to find the duplicate elements in a given array of integers. Return -1 If there are no such elements.

In [58]:
# write your answer here
from array import *;
my_array = array('i', [1,2,3,4,5,1,2,3,4,23,32,45,32,21,23])
def Repeat(x): 
    _size = len(x) 
    repeated = [] 
    for i in range(_size): 
        k = i + 1
        for j in range(k, _size): 
            if x[i] == x[j] and x[i] not in repeated: 
                repeated.append(x[i]) 
    if not repeated:
      print('No Duplicates!')
      return -1;
    else:
      print('Duplicates:')
      return repeated;
print (Repeat(my_array)) 



Duplicates:
[1, 2, 3, 4, 23, 32]


(2) Write a Python program to select all the Sundays of a specified year.



In [33]:
# write your answer here
from datetime import date, timedelta
def all_sundays(year):
       dt = date(year, 1, 1)     
       dt += timedelta(days = 6 - dt.weekday())  
       while dt.year == year:
          yield dt
          dt += timedelta(days = 7)
input_year=int(input('Enter the Year:'))
for s in all_sundays(input_year):
   print(s)

Enter the Year:1996
1996-01-07
1996-01-14
1996-01-21
1996-01-28
1996-02-04
1996-02-11
1996-02-18
1996-02-25
1996-03-03
1996-03-10
1996-03-17
1996-03-24
1996-03-31
1996-04-07
1996-04-14
1996-04-21
1996-04-28
1996-05-05
1996-05-12
1996-05-19
1996-05-26
1996-06-02
1996-06-09
1996-06-16
1996-06-23
1996-06-30
1996-07-07
1996-07-14
1996-07-21
1996-07-28
1996-08-04
1996-08-11
1996-08-18
1996-08-25
1996-09-01
1996-09-08
1996-09-15
1996-09-22
1996-09-29
1996-10-06
1996-10-13
1996-10-20
1996-10-27
1996-11-03
1996-11-10
1996-11-17
1996-11-24
1996-12-01
1996-12-08
1996-12-15
1996-12-22
1996-12-29


(3) Python files reading and writing. Download the “[exercise_02_data _collection.zip](https://github.com/unt-iialab/INFO5731_Spring2020/blob/master/In_class_exercise/exercise_02_data_collection.zip)” to your local and un-zip it.

*   Write a program to read all the txt files and save the sentences in all the files into one csv file with two columns, the first column is sentence id (txt file name+sentence line number), the second column is the sentence text content.
*   Remove all the punctuations from the sentences, save the processed sentences into a new column in the same csv file.
*   Ask the user to enter a word, return all the sentences that include this word, three kinds of information should be returned: sentence id, sentence text content, the count that user input word appear in the sentence..



In [74]:
import os
from google.colab import files
uploaded = files.upload()

Saving ARTHROTEC.1.txt to ARTHROTEC.1 (1).txt
Saving ARTHROTEC.2.txt to ARTHROTEC.2 (1).txt
Saving ARTHROTEC.3.txt to ARTHROTEC.3 (1).txt
Saving ARTHROTEC.4.txt to ARTHROTEC.4 (1).txt
Saving ARTHROTEC.5.txt to ARTHROTEC.5 (1).txt
Saving ARTHROTEC.6.txt to ARTHROTEC.6 (1).txt
Saving ARTHROTEC.7.txt to ARTHROTEC.7 (1).txt
Saving ARTHROTEC.8.txt to ARTHROTEC.8 (1).txt
Saving ARTHROTEC.9.txt.txt to ARTHROTEC.9.txt (1).txt
Saving ARTHROTEC.10.txt to ARTHROTEC.10 (1).txt
Saving ARTHROTEC.11.txt to ARTHROTEC.11 (1).txt
Saving ARTHROTEC.12.txt to ARTHROTEC.12 (1).txt
Saving ARTHROTEC.13.txt to ARTHROTEC.13 (1).txt
Saving ARTHROTEC.14.txt to ARTHROTEC.14 (1).txt
Saving ARTHROTEC.15.txt to ARTHROTEC.15 (1).txt
Saving ARTHROTEC.16.txt to ARTHROTEC.16 (1).txt
Saving ARTHROTEC.17.txt to ARTHROTEC.17 (1).txt
Saving ARTHROTEC.18.txt to ARTHROTEC.18 (1).txt
Saving ARTHROTEC.19.txt to ARTHROTEC.19 (1).txt
Saving ARTHROTEC.20.txt to ARTHROTEC.20 (1).txt
Saving ARTHROTEC.21.txt to ARTHROTEC.21 (1).txt
Sa

In [0]:
import pandas as pd;
col_id=[]
out=[]
new_list=[]
sentences=[]
for file in uploaded:
  with open(file, 'r') as f:
     text = f.read()
     sentences=text.splitlines()
     length=len(sentences)
     for j in range(length):
       col_id.append(file+'.'+str(j))
     for i in sentences:
       out.append(i)
with open('output.csv', 'w') as f:
    writer = csv.writer(f)
    for val in out:
        writer.writerow([val])
data1= pd.read_csv("output.csv",names=['text'])
data2= pd.DataFrame(col_id,columns=['Sentence_ID']) 
result = pd.concat([data1,data2],axis=1)
#result['Sentence_ID','text']
result = result.reindex(columns=['Sentence_ID','text'])
result.to_csv('Final.csv')
#check output in csv file generated

In [132]:
result["No_Punctuation"] = result['text'].str.replace('[^\w\s]','')
result

Sentence_ID  ...                                     No_Punctuation
0      ARTHROTEC.1.txt.0  ...  I feel a bit drowsy  have a little blurred vis...
1      ARTHROTEC.1.txt.1  ...  Ive been on Arthrotec 50 for over 10 years on ...
2      ARTHROTEC.1.txt.2  ...  Due to my arthritis getting progressively wors...
3      ARTHROTEC.1.txt.3  ...  every day for the next month to see how I get ...
4      ARTHROTEC.1.txt.4  ...  So far its been very good pains almost gone bu...
..                   ...  ...                                                ...
530  ARTHROTEC.100.txt.3  ...                           canker sores in my mouth
531  ARTHROTEC.100.txt.4  ...                                           headache
532  ARTHROTEC.100.txt.5  ...            been off for 1 week still have bleeding
533  ARTHROTEC.100.txt.6  ...                               helped my pain alot 
534  ARTHROTEC.100.txt.7  ...                 too scared to take this drug again

[535 rows x 3 columns]

In [185]:
word=input('Enter the word to search=')
result_2=result[result['text'].str.contains(word,na=False)]
del result_2['No_Punctuation']
result_3=result_2.text.str.count(word).to_frame(name='Frequency in sentence')
final = pd.concat([result_2,result_3],axis=1)
final

Enter the word to search=head


Sentence_ID  ... Frequency in sentence
34     ARTHROTEC.7.txt.0  ...                     2
79    ARTHROTEC.16.txt.4  ...                     1
91    ARTHROTEC.17.txt.6  ...                     1
183   ARTHROTEC.31.txt.0  ...                     1
194   ARTHROTEC.34.txt.0  ...                     1
220   ARTHROTEC.39.txt.1  ...                     1
236   ARTHROTEC.41.txt.5  ...                     1
239   ARTHROTEC.42.txt.0  ...                     1
393   ARTHROTEC.70.txt.4  ...                     1
412   ARTHROTEC.75.txt.0  ...                     1
422   ARTHROTEC.77.txt.0  ...                     1
437   ARTHROTEC.80.txt.0  ...                     1
448   ARTHROTEC.83.txt.0  ...                     1
492   ARTHROTEC.93.txt.1  ...                     1
531  ARTHROTEC.100.txt.4  ...                     1

[15 rows x 3 columns]


(4) Install packages nltk, numpy, scipy, pandas, and sklearn on Google Colab. Write a program to test whether they are installed successfully. 

In [166]:
import nltk
nltk.download()

NLTK Downloader
---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> d

Download which package (l=list; x=cancel)?
  Identifier> all
       | 
       | Downloading package abc to /root/nltk_data...
       |   Unzipping corpora/abc.zip.
       | Downloading package alpino to /root/nltk_data...
       |   Unzipping corpora/alpino.zip.
       | Downloading package biocreative_ppi to /root/nltk_data...
       |   Unzipping corpora/biocreative_ppi.zip.
       | Downloading package brown to /root/nltk_data...
       |   Unzipping corpora/brown.zip.
       | Downloading package brown_tei to /root/nltk_data...
       |   Unzipping corpora/brown_tei.zip.
       | Downloading package cess_cat to /root/nltk_data...
       |   Unzipping corpora/cess_cat.zip.
       | Downloading package cess_esp to /root/nltk_data...
 

True

In [167]:
pip install nltk

In [171]:
from nltk.tokenize import sent_tokenize, word_tokenize
EXAMPLE_TEXT = "Hello Deepak sai paty, how are you doing today?The weather is great, and Python is awesome. The sky is blue. Denton is college town."
print(sent_tokenize(EXAMPLE_TEXT))


['Hello Deepak sai paty, how are you doing today?The weather is great, and Python is awesome.', 'The sky is blue.', 'Denton is college town.']


In [172]:
pip install numpy;

In [174]:
 import numpy as np 
a = np.array([[3, 1], 
			[9, 8]]) 
b = np.array([[2, 1], 
			[7, 8]]) 
print ("Array sum:\n", a + b) 
print ("Array multiplication:\n", a*b) 
print ("Matrix multiplication:\n", a.dot(b)) 


Array sum:
 [[ 5  2]
 [16 16]]
Array multiplication:
 [[ 6  1]
 [63 64]]
Matrix multiplication:
 [[13 11]
 [74 73]]


In [175]:
pip install scipy

In [177]:
from scipy.special import cbrt
cb = cbrt([27, 64])
print(cb)

[3. 4.]


In [178]:
pip install pandas

In [179]:
import pandas as pd
df = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]});
print(df)

    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


In [181]:
pip install scikit-learn

In [182]:
from sklearn import datasets
iris= datasets.load_iris()
print(iris.data.shape)

(150, 4)
